version: '3.7'

services:
  prediction_model:
    build: ./prediction_model
#    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./prediction_model:/usr/src/app
    ports:
      - 5000:80
    env_file:
      - ./.env.dev
